### ISSUE TITLE
Band bass filter

### ISSUE THREAD

**Issue by JoeCleveland** [JoeCleveland/ASEFinal_WahWah#5]
Find implementation for band pass filter in rust (Or implement if you can)

**Comment by frshdjfry** [comment]
There is an exiting well implemented solution for FIR bandpass filter here:

https://docs.rs/sdr/0.7.0/sdr/fir/struct.FIR.html#method.bandpass

There's another simpler solution here:

https://github.com/gyng/synthrs/blob/77e062f3e40304dd2c3611d70ece6a0e4eaf9750/src/filter.rs#L116
